name: libraccio_extractor
description: A Flutter library for extracting book data from libraccio.it
version: 0.1.0
repository: 
environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  html: ^0.15.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
